export {default as Button} from './Head/Button.jsx'
export {default as Head} from './Head/Head.jsx'
export {default as NavBar} from './Head/Navbar.jsx'
export {default as SectionOne} from './Main/SectionOne.jsx'
export {default as SectionTwo} from './Main/SectionTwo.jsx'
export {default as Testimonies} from './Main/Testimonies.jsx'
export {default as Footer} from './Main/Footer.jsx'
export {default as Residents} from './PagesComponent/Residents.jsx'
export {default as Industrial} from './PagesComponent/Industrial.jsx'
export {default as Warehouse} from './PagesComponent/Warehouse.jsx'
// export {default as } from ''
// export {default as } from ''
// export {default as } from ''